apiVersion: simulation.c930.net/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: simulated-workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
spec:
  simulationType: CPU
  duration: 10
  intensity: 10
  # TODO(user): Add fields here
