apiVersion: simulation.c930.net/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/name: simulated-workload-operator
    app.kubernetes.io/managed-by: kustomize
  name: workload-sample
spec:
  simulationType: Memory
  duration: 5
  intensity: 10
  dependentResources:
    - resourceType: "Deployment"
      quantity: 1
#      template:
#        apiVersion: v1
#        kind: Pod
#        metadata:
#          generateName: example-pod-
#        spec:
#          containers:
#            - name: example-container
#              image: nginx
#              command: [ "echo", "Simulating Memory Load" ]
#    - resourceType: "ConfigMap"
#      quantity: 2
#      template:
#        apiVersion
